### ISSUE TITLE
app added to url in 0.3.0

### ISSUE THREAD

**Issue by andrewkenreich** [crabnebula-dev/devtools#218]
![image](https://github.com/crabnebula-dev/devtools/assets/23067478/10de2f4c-1aee-415b-ae85-c48fcd93b575)

Not sure if this is on my end or something new introduced but the URL given doesn't match from the CLI to the docs - so CLI I get this - 

![image](https://github.com/crabnebula-dev/devtools/assets/23067478/b9345311-8ee7-4c2f-972d-738c6782375f)

**Comment by lucasfernog-crabnebula** [comment]
Thank you for reporting this!
