### ISSUE TITLE
Off by one error when logging using `tracing`

### ISSUE THREAD

**Issue by bicarlsen** [crabnebula-dev/devtools#315]
When using `tracing` for logging, outputs are delayed by one event.
e.g.
```rust
tracing::debug!("1") // No log output.
...
tracing::debug!("2") // Logs "1".
...
tracing::debug!("3") // Logs "2". All subsequent logs are delayed by one logging event.
```

**Comment by bicarlsen** [comment]
I created an [MRE](https://github.com/bicarlsen/tauri-devtools-logging-off-by-one-error).

**Comment by johann-crabnebula** [comment]
Thanks for reporting and creating a MRE. 
Will look into this now :)

**Comment by johann-crabnebula** [comment]
At this point it looks a lot like a frontend issue. I still need to investigate a little more.

**Comment by johann-crabnebula** [comment]
I think I found the issue. There might just be something broken with the way the filtering is implemented (even the default one). After my colleagues check the changes, we will roll an update and let you know.

See the changes here #317

**Comment by johann-crabnebula** [comment]
The Fix PR just got merged. The release for Premium will probably happen next week. 

Web DevTools is already up to date. @bicarlsen can you check if the problem is fixed for you?

**Comment by bicarlsen** [comment]
Yep! All fixed :)
