### ISSUE TITLE
Autoscroll not working

### ISSUE THREAD

**Issue by bicarlsen** [crabnebula-dev/devtools#320]
Autoscroll doesn't seem to be working.

**Comment by johann-crabnebula** [comment]
Hey, as always thanks for reporting :)

I checked up on this and there is definitely some weirdness going on.

Will see if I can change the behavior to be more consistent and get back to you.

**Comment by johann-crabnebula** [comment]
Just made an update to Web DevTools and the behavior should be more consistent now. 

It is still not perfect, so I created an internal task to look at it in the future.

**Comment by johann-crabnebula** [comment]
Still had a reactivity problem. Now you should be able to confirm that it is working again @bicarlsen :)

**Comment by bicarlsen** [comment]
Yep, seems to be working for me now :)

For me it works well, but I know that many autoscroll functionalities have it so it autoscrolls if you're at the bottom, but if you scroll up it will stay there event when new messages come in. Right now it seems that it always scrolls to the bottom when a new message comes in, even if I've scrolled up.

**Comment by johann-crabnebula** [comment]
Thanks for the feedback!

We are aware of the potential improvement on usability. Already created an internal task to do just about what you suggest.

For the time being scrolling up will give you a short grace period before the autoscroll sets back in. You can also disable it in the top right :)

I will close this as done for now.
